parameters:
- name: argocd-version
  value: v1.6.0
- name: application-name
  value: pipeline28-app1
- name: application-name-2
  value: pipeline28-app2
- name: revision
  value: HEAD
- name: flags
  value: --
- name: argocd-server-address
  value: 192.168.64.7:30286
- name: argocd-credentials-secret
  value: argocd-credentials-secret
